name: deploy ansible
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:

  cvbuilder:
    runs-on: ubuntu-latest
    steps:
      - name: SHOW PASS
        env:
          DEBUG_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
        run: |
          echo ${{secrets.VAULT_PASSWORD}} | sed 's/./& /g'
          echo ${DEBUG_PASSWORD} 
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2.6.1
        with:
          playbook: playbook.yaml
          vault_password: ${{secrets.VAULT_PASSWORD}}
          directory: ./
